<?php

namespace app\components;
use yii\base\Widget;
use Yii;
//виджет обертка страница общего вывода с помощью bootstrap стиля card
//для использования необходимо в параметрах метода виджета begin указать dataProvider и name(имя таблицы)
class GridViewPatternWidget extends Widget
{
    public $gridview;
    public $dataProvider;
    public $name;



    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ob_start();
    }

    public function run()
    {
        $this->gridview = ob_get_clean();
        return $this->render('gridviewpattern',['gridview'=>$this->gridview, 'dataProvider'=>$this->dataProvider,'name'=>$this->name]);
    }


}